### PR TITLE
new name - ossm console

### PR DESCRIPTION
**Pull request by jmazzitelli**
fixes: https://github.com/kiali/openshift-servicemesh-plugin/issues/70

### CODE REVIEW

**Comment by jmazzitelli** [comment]
To test:

1. The install guide and its screenshots have changed - take a quick look at those.
2. `make cluster-push operator-create install-cr` should install and run correctly - confirm you still get "Service Mesh" options in the OS Console once it all deploys.
3. `make uninstall-cr` should remove the plugin cleanly (`oc get consoleplugins.console.openshift.io` returns no resources and the Service Mesh tabs go away from the OS Console).
4. `make validate-cr` is successful (which validates the example CR)
5. `make validate-olm-metadata` is successful (which validates the 2 sets of OLM metadata)
6. `make MOLECULE_SCENARIO="default config-values-test" molecule-test` should run and pass the molecule tests
7. `make operator-delete` cleans up everything
8. `make run-playbook` and `make run-operator` runs the operator successfully. (this requires you to have python and ansible set up on the local machine)

**Comment by jmazzitelli** [comment]
When we merge this, we need to delete the old quay repos:
* https://quay.io/repository/kiali/servicemesh-plugin
* https://quay.io/repository/kiali/ossmplugin-operator

**Comment by josunect** [comment]
**make cluster-push operator-create install-cr**

I had a first error in the step: 

```
/home/jcordoba/dev/openshift-servicemesh-plugin/operator/_output/operator-sdk-install/opm render --skip-tls-verify default-route-openshift-image-registry.apps-crc.testing/kiali/ossmconsole-operator-bundle:v0.1.0 --output yaml >> /home/jcordoba/dev/openshift-servicemesh-plugin/operator/_output/index/ossmconsole-index/index.yaml
2022/08/31 10:37:21 render reference "default-route-openshift-image-registry.apps-crc.testing/kiali/ossmconsole-operator-bundle:v0.1.0": error resolving name : failed to authorize: failed to fetch oauth token: unexpected status: 401 Unauthorized
make: *** [make/Makefile.olm.mk:68: build-olm-index] Error 1
```

I had to login with docker also in order for this to work.

image


**make uninstall-cr**
Ok

**Validate CR**

Validating the CR:
----------
testossmconsole.kiali.io/ossmconsole created
----------
OSSMConsole CR [/home/jcordoba/dev/openshift-servicemesh-plugin/operator/crd-docs/cr/kiali.io_v1alpha1_ossmconsole.yaml] is valid.

**make validate-olm-metadata**
INFO[0000] All validation tests have completed successfully 

**make MOLECULE_SCENARIO="default config-values-test" molecule-test**
Ok

**make operator-delete**
Ok

image

**Comment by jmazzitelli** [comment]
Yes, sorry. You need to log into the image registry to push. This is mentioned in our quick install steps: https://github.com/kiali/openshift-servicemesh-plugin#quick-summary

**Comment by jmazzitelli** [comment]
OK, @josunect has validated almost everything. I can confirm the dev targets "run-playbook" and "run-operator" work. I'm going to merge.

**Comment by jmazzitelli** [comment]
> When we merge this, we need to delete the old quay repos:
> 
> * https://quay.io/repository/kiali/servicemesh-plugin
> * https://quay.io/repository/kiali/ossmplugin-operator

this is done - they have been deleted.

**Comment by josunect** [comment]
> Yes, sorry. You need to log into the image registry to push. This is mentioned in our quick install steps: https://github.com/kiali/openshift-servicemesh-plugin#quick-summary

Yes, it was weird. I was successfully logged in with podman - And the previous push have worked. But then, it failed. So I also logged in to docker. Probably it was something odd in my environment.

**Comment by josunect** [comment]
Adding the missing tests (I needed to install ansible, as instructed): 

**make run-playbook**

I think that finalized correctly: 
image


**make run-operator**

It looks to wait here: 

image

I guess this is the way it is expected to work.

**Comment by jmazzitelli** [comment]
> I guess this is the way it is expected to work.

Yup! Exactly. This runs just like the operator if it were deployed normally in the cluster. The make target creates a CR that causes the operator to immediately process it - then the operator sits and waits for changes to that CR. Had you edited that CR (oc edit ossmconsole ossmconsole -n ossmconsole) you would have seen the operator "wake up" and reconcile it again. This is mentioned here: https://github.com/kiali/openshift-servicemesh-plugin#make-run-operator where it says `The operator will immediately reconcile the CR and then sit and wait for changes made to the CR, which will trigger another reconciliation.`

**Pull request merged**
