### PR TITLE
be able to push plugin into cluster and test it

### PR DESCRIPTION
**Pull request by jmazzitelli**
This adds the ability to build the plugin and operator locally, push it to your cluster, and run/test it. It no longer relies on the developer pushing their "latest" image to quay in order to pull/install it (obviously, we did not want that because if you have multiple developers working on the plugin, they will all be overwriting everyone's latest image on quay).

One thing this changes in the previous make targets is the following: make target `build-plugin-push` has been renamed `push-plugin-image` for consistency (this target doesn't build the plugin - it only pushes an already-built plugin). It also by default pushes a `:dev` tag, not `:latest`, you need to set an env var to tell it you want to tag with `:latest`. This is for technical reasons (to make it easier for everything else to work). Therefore, what was done via `make build-plugin-push` is now done via `make -e CONTAINER_VERSION=latest build-plugin-image push-plugin-image`.

This change should be OK because devs aren't regularly pushing to quay anyway - our releases in the future will be pushed to quay via CI workflows, and they will be implemented to invoke that new `push-plugin-image` target with the correct version (as is done today for the kiali releases).

### CODE REVIEW

**Comment by jmazzitelli** [comment]
Some things you can try to see everything work. To start, you need to `oc login` to an OpenShift 4.10 cluster and have Istio and Kiali installed.

1. Build the plugin: `make build-plugin`
2. Create a "latest" plugin image and push to quay (note: this only shows you how it is done - we really want the CI workflow to do this; devs normally should not do this manually): `make -e CONTAINER_VERSION=latest build-plugin-image plugin-push-image`. Assuming you have permission and you are logged into quay.io, you will see the image here: https://quay.io/repository/kiali/servicemesh-plugin?tab=tags
3. Run the cluster-status make target which will expose the internal image registry of your cluster and tell you what command to use to log into that registry: `make cluster-status`.
4. Look at the bottom of that `make cluster-status` output and find the `podman login` command you need to use to log into the internal image registry (see the command labeled "Image Registry login:"). Run that command to log into your cluster's image registry.
5. Build and push the plugin and operator images to your local cluster's internal image registry: `make cluster-push`
6. Install the operator via OLM using the command `make operator-create`
7. Go to the OpenShift Console's _Operators>InstalledOperators_ page to confirm the OpenShift Service Mesh Plugin Operator has been successfully installed.
8. Confirm your operator is using the locally built operator image you pushed into the internal registry - the operator Pod's container image should be "_image-registry.openshift-image-registry.svc:5000/kiali/ossmplugin-operator:dev_":
```
$ oc get pods -n openshift-operators -l app.kubernetes.io/name=ossmplugin-operator -o jsonpath='{.items[0].spec.containers[0].image}' && echo 
image-registry.openshift-image-registry.svc:5000/kiali/ossmplugin-operator:dev
```
9. Install an OSSMPlugin CR and tell the operator to install the plugin using your locally built plugin image: `make install-cr`
10. Confirm your plugin has been deployed by the operator by looking at your OpenShift Console UI and see that you have a _Service Mesh_ option on the left-hand menu. You will have a wait for a few seconds (perhaps as much as 30 seconds) for the plugin to be deployed and the OpenShift Console UI to detect and install it. You know the OpenShift Console has detected and installed the plugin when it pops up a message that says, "Web console update is available. There has been an update to the web console. Ensure any changes have been saved and refresh your browser to access the latest version." Refresh the OpenShift Console UI browser tab and you should see the new _Service Mesh_ menu option.
11. Confirm that your plugin is using your locally built plugin image you pushed into the internal registry - the plugin Pod's container image should be "_image-registry.openshift-image-registry.svc:5000/kiali/servicemesh-plugin:dev_":
```
$ oc get pods -n ossmplugin -l app.kubernetes.io/name=ossmplugin -o jsonpath='{.items[0].spec.containers[0].image}' && echo 
image-registry.openshift-image-registry.svc:5000/kiali/servicemesh-plugin:dev
```

At this point, you have confirmed you can locally build from source code both the plugin and operator and that you can deploy both into OpenShift. The OpenShift Console UI now has the locally built plugin that you can now interact with.

12. Uninstall the plugin, but leave the operator running: `make uninstall-cr`
13. Give it a few seconds and you will see the plugin will have been removed and the OpenShift Console UI will inform you that it has been updated and you should refresh the console browser tab. Refresh the Console and the _Service Mesh_ left-hand menu option will no longer appear. Confirm the plugin is no longer deployed: `oc get pods -n ossmplugin`
14. Finally, run the "config-values-test" molecule test, making sure you test with your plugin image you built locally (aka the "dev image"): `make -e MOLECULE_USE_DEV_IMAGES="true" MOLECULE_SCENARIO="config-values-test" molecule-test`

**Comment by jmazzitelli** [comment]
@lucasponce I documented the test procedure steps above if you want to see it all work. I ran all of these steps and they work for me.

At this point, the operator and plugin dev environment should be set up for everyone to be able to use now.

We are also ready to start publishing tech-preview releases whenever we want. The infrastructure is here. This means we can start publishing to the Red Hat community catalog whenever we think we are ready. The OLM manifests are ready and we can push these to a "candidate" OLM channel (basically, that says this is in "alpha" or "tech preview" stage). It will allow anyone with a Red Hat OpenShift installation to see "OpenShift Service Mesh Plugin" in their OperatorHub script and install this.

**Comment by lucasponce** [comment]
I've tested and it works fine.
But I've found one problem running the molecule-test:

```
$ make -e MOLECULE_SCENARIO="config-values-test" -e MOLECULE_USE_DEV_IMAGES="true" molecule-test
STEP 1/5: FROM quay.io/ansible/toolset:3.5.0
Trying to pull quay.io/ansible/toolset:3.5.0...
Error: error creating build container: initializing source docker://quay.io/ansible/toolset:3.5.0: reading manifest 3.5.0 in quay.io/ansible/toolset: unauthorized: access to the requested resource is not authorized
make: *** [make/Makefile.molecule.mk:79: molecule-build] Error 125
```

Just in case that this step needs some config that is not described.

**Comment by lucasponce** [comment]
Anyway, on these first steps, unless a blocker, I think that consolidating and iterating are good.

**Review by lucasponce — APPROVED** [review]

**Comment by jmazzitelli** [comment]
> Error: error creating build container: initializing source docker://quay.io/ansible/toolset:3.5.0: reading manifest 3.5.0 in quay.io/ansible/toolset: unauthorized: access to the requested resource is not authorized

Looks like quay is having a problem. Either that, or you are required to be logged into quay to pull that? But that doesn't sound right. I'm thinking its a problem with quay.

**Comment by jmazzitelli** [comment]
hmm.. I got the same thing when I removed my local copy of that image:
```
$ make -e FORCE_MOLECULE_BUILD=true molecule-build
STEP 1/5: FROM quay.io/ansible/toolset:3.5.0
Trying to pull quay.io/ansible/toolset:3.5.0...
Error: error creating build container: initializing source docker://quay.io/ansible/toolset:3.5.0: reading manifest 3.5.0 in quay.io/ansible/toolset: unauthorized: access to the requested resource is not authorized
```
Unbelievable -- it looks like they removed that repo. This is like the second time I've seen it where people have completely removed artifacts breaking things: https://quay.io/repository/ansible/toolset

**Pull request merged**
