### PR TITLE
Update start-console

### PR DESCRIPTION
**Pull request by aljesusg**
Fix https://github.com/kiali/openshift-servicemesh-plugin/issues/73

This update from https://github.com/openshift/console-plugin-template/blob/main/start-console.sh fix my local env.

### CODE REVIEW

**Comment by jmazzitelli** [comment]
This "works" - I do not get that error anymore. I do see the plugin in the local console:
image

BUT! I cannot see Kiali UI. When I try to log in, I get this:
image

I can confirm I am able to log in the Kiali route directly and see the Kiali UI. So the standalone Kiali is installed and working. I just can't see it in the plugin because it always asks me to log in, but the log in fails. This log-in issue is a known  problem, but in the past, we just had to log into the standalone Kiali and our login token will remain and the plugin never asked to log in again. It looks like this behavior is different when running in this local mode.

We can merge this PR though. It think this login issue is different than the network issue this PR fixed.

**Review by jmazzitelli — APPROVED** [review]
see my notes about the additional problem I see. But we can merge this PR since that is a different problem.

**Comment by aljesusg** [comment]
Well. I can see all but I am running ./kiali/hack/run-kiali.sh that exposed kiali locally without authentication.
My next steps is move this to native and fix the authentication. But we can use the local env

**Review by josunect — APPROVED** [review]
Works as expected: 
image

image

(Tested in crc 2.13)

**Pull request merged**
