### PR TITLE
Define environment variables to Core UI library

### LINKED ISSUE #135: Passing global parameters to library
For the moment there are some global values defined in Openshift Service Mesh Plugin that need to be used in the Core UI library:
- Kiali Proxy url
- CSS classname prefix

First, define what is the best approach to do it and then implement it both in library and OSSMC.

### PR DESCRIPTION
**Pull request by ferhoyos**
Closes #135.

### CODE REVIEW

**Comment by aljesusg** [comment]
Please @ferhoyos Rebase this one to verify the changes and change the css_prefix to **ossmc_plugin_** in production mode

**Comment by ferhoyos** [comment]
Done

**Comment by aljesusg** [comment]
> Done

I launched the release version 0.9.0

but you still need to make some changes in Overview page to merge this one. at least I am seeing errors locally

**Review by aljesusg — CHANGES_REQUESTED** [review]
I launched the release version 0.9.0

but you still need to make some changes in Overview page to merge this one. at least I am seeing errors locally

**Comment by ferhoyos** [comment]
Updated core-ui to version 0.9.0 and removed proxyUrl from OverviewPage. Please review it again @aljesusg.

**Pull request merged**
