### PR TITLE
Copy code and configuration from kiali repository

### LINKED ISSUE #159: Align configuration with kiali repository
Since Kiali application is going to be copied directly from [#kiali/kiali](https://github.com/kiali/kiali) repository without any modification possible, it is necessary that OSSMC plugin is aligned with the following configuration:

- Same typescript settings (tsconfig.json)
- Similar webpack configuration (use of babel-loader + typescript checks)
- Same lint configuration (eslint and prettier)
- Same editor config (.editorconfig)

### PR DESCRIPTION
**Pull request by ferhoyos**
Closes #159.

`plugin/src/kiali` is just a copy from kiali/kiali repository, so you have to review only the files outside this folder.

### CODE REVIEW

**Comment by jmazzitelli** [comment]
When merging this PR, make sure to retain that first commit's commit message (it contains the necessary information to get back to the initial source of the copy).

**Comment by ferhoyos** [comment]
> When merging this PR, make sure to retain that first commit's commit message (it contains the necessary information to get back to the initial source of the copy).

I have created a README file containing this information. I hope this can be generated automatically by the script in the future.

**Comment by hhovsepy** [comment]
Hi @ferhoyos , can you provide testing steps with this PR, when plugin is run, the Kiali UI is run from plugin/src/kiali.

**Comment by ferhoyos** [comment]
Hi @hhovsepy, from the moment Kiali UI is not run, only copied and compiled. Testing step for this PR is that nothing is broken and plugin works as always. 

Kiali UI from plugin/src/kiali will be run in https://github.com/kiali/openshift-servicemesh-plugin/issues/160 when iframes are replaced by wrappers. In that PR only the Kiali UI code is copied and configuration modified to compile the code correctly.

**Comment by jmazzitelli** [comment]
> I have created a README file containing this information. I hope this can be generated automatically by the script in the future.

That's this PR: https://github.com/kiali/openshift-servicemesh-plugin/pull/167

**Review by hhovsepy — APPROVED** [review]
Regression tested the console plugin, works as expected.

**Pull request merged**
