### PR TITLE
Adapt OSSMC to PF5

### LINKED ISSUE #198: Adapt OSSMC to PF5
Kiali application has been recently updated to Patternfly version 5 (https://github.com/kiali/kiali/issues/6446). OSSMC has to be adapted to support PF5 too.

### LINKED ISSUE #279: Internationalization (I18N) support for OSSMC
Now that Kiali application has added i18n support (https://github.com/kiali/kiali/pull/6843), OSSMC has to be configured to use OpenShift console language and translate native labels of IstioConfigList page and menu navigation entries.

### LINKED ISSUE #284: Traffic graph context menu options do not redirect to the correct pages
### Describe the bug

Every node in the traffic graph has a context menu containing links to specific pages for that node (details, traffic, logs, etc.). However, none of the links redirect to the correct page within the OpenShift console.

image

### Expected Behavior

Each link in the context menu's node should redirect to correct page for that node.

### What are the steps to reproduce this bug?

1. Go to the traffic graph page
2. Click on the context menu of any node
3. Select any of the link options
4. Check that nothing happens

### Environment

- **OSSMC/Kiali version:** 1.73
- **OpenShift version:** 4.13
- **Istio version:** 1.18

### LINKED ISSUE #300: Multiple redirections when clicking on internal links
### Describe the bug

When the user click on an internal link of OSSMC, for example selecting the workload related to a specific service, the console sometimes perform multiple redirections before landing on the desired page. Then, if the user clicks on back button, the console does not navigate to the previous page but to a "Not Found" page or random console page (dashboard, project list, etc.).

For OCP 4.15, sometimes the redirection occurs after landing to the desired page, displaying a wrong page to the user.

### Expected Behavior

The console should navigate to the desired page when the user clicks on an internal link

### What are the steps to reproduce this bug?

1. Go to the istio config list page
2. Click on any istio item
3. In the Service Mesh tab, click on any reference
4. Verify that the console navigates to the desired reference page
5. Click on the browser back button
6. Verify that the console does not navigate to the previous page

image

image

image

### Environment

- **OSSMC/Kiali version:** 1.73
- **OpenShift version:** 4.12 - 4.15
- **Istio version:** 1.18

### PR DESCRIPTION
**Pull request by ferhoyos**
### Describe the change
With the release of Openshift 4.15 featuring Patternfly version 5, it is now possible to incorporate the latest Kiali code into the OSSMC repository. This PR upgrades the OSSMC application to support PF5.

Changes made to adapt OSSMC to PF5:
- Upgraded PF and dynamic plugin SDK libraries
- Replaced `Jaeger` by `Tracing` in OSSMC wrapper
- Added MeshDataStateReducer to reducers

During the PR review, the `plugin/src/kiali` folder can be ignored as it is a direct copy from the Kiali repository.

**Bonus:** Align ESLint rules with the Kiali repository and apply them exclusively to the `src/openshift` folder. The `src/kiali` directory is simply a copy from the Kiali repository and can be ignored)

### Steps to test the PR
1. This PR is compatible with the latest Istio and Kiali versions (1.21 and 1.82 respectively).
2. Run OpenShift Console 4.15 to test this PR. Althoug CRC has not been upgraded to that version yet, you can set the specific version 4.15 in `plugin/start-console.sh` to replace the OpenShift console of your local CRC with that version for local testing:

```
OPENSHIFT_VERSON=4.15
```

Afterward, navigate to `http://localhost:9000` and verify that OSSMC operates correctly in the OpenShift 4.15 console with PF5.

### Automation testing
Not applicable as this PR is an upgrade

### Issue reference
Closes #198
Closes #279 
Fixes #284 
Fixes #300

### CODE REVIEW

**Review by josunect — COMMENTED** [review]
I was doing some tests with the latest Kiali version, overall seems to be working fine, nice job!  

image
image

image


Things that I've found not looking as expected: 

image

image

(Maybe this was not working but if I click in the details, nothing happens): 

image

The modal for a custom time range: 

image


The traces tab for a workload/service returns a 404: 

image

Note: Tested with CRC version: 2.31.0+6d23b6 and the configuration indicated in the PR

**Comment by ferhoyos** [comment]
Thanks for the feedback Josune!

I have reviewed the issues you mentioned:
- Context menu issue affects version v1.73 as well. I have created an issue [here](https://www.github.com/kiali/openshift-servicemesh-plugin/issues/284)
- The modal issue is related to PF5 and how it renders modals within the OpenShift console.
- The traces/tab issue is due to a badly formatted request body sent by the plugin to the Kiali server. This was added recently to Kiali because it does not affect OSSMC v1.73.

**Comment by ferhoyos** [comment]
@josunect I have fixed the context menu and traces/tab issues. The modal issue is due to a bug in the Openshift Console Dynamic SDK. It is already reported but we will have to wait until a fix is released. Since the modal issue does not block anything I think the best approach is to ignore it for the moment and upgrade the sdk in a future PR when the fix is released.

**Comment by ferhoyos** [comment]
Waiting for https://github.com/kiali/kiali/pull/7224 to complete the PR

**Comment by ferhoyos** [comment]
https://github.com/kiali/kiali/pull/7224 is merged. The PR is ready for review.

**Review by josunect — COMMENTED** [review]
Thank, Fernando for addressing those issues. 

A small thing I've seen in the tags visualization: 

image

The style with the bullets has not been adjusted. 

One thing I've seen is this characters: 

image

I guess this is because we are using CRC 4.14 and it does not support this i18n funcions? 

When I click on the Istio Config I've seen this error: 

image

This seems to be just for the "All Projects" and maybe the error is also in other versions, so probably we can create an additional issue to fix it.

**Comment by ferhoyos** [comment]
Thanks @josunect for the feedback! I have tested with OCP 4.15 and the issues remain, so it is not caused by the OCP version.

I have fixed the bullet style and the error when you get the config list for all namespaces.

Regarding the i18n issue, I don't know exactly what is happening. Maybe it is related with our i18n configuration. Just in case, I am going to add changes from PR https://github.com/kiali/openshift-servicemesh-plugin/pull/271, where I have i18n working for OCP 4.14.

**Comment by ferhoyos** [comment]
I have fixed the i18n configuration issue. To do that I have included the content of PR #271 into this PR, so you will have to review the i18n support too.

image

@josunect @jshaughn the PR is ready for review again.

**Review by josunect — COMMENTED** [review]
The other issues have been fixed, one more small thing that I've seen is in the spans menu: 

image

Maybe the headers can be adjusted?

**Review by josunect — APPROVED** [review]
All comments have been addressed. CORS solved from last commit. 

Code LG.

**Comment by jmazzitelli** [comment]
I'm trying to test this PR but failing. Can you provide detailed test procedures?

I did the following.

1. Install CRC, log into and log into the cluster. From kiali/kiali repo, run:
```
hack/crc-openshift.sh start
oc login -u kiali -p kiali --server https://api.crc.testing:6443/
podman login --tls-verify=false -u kiali -p $(oc whoami -t) default-route-openshift-image-registry.apps-crc.testing
```
2. Install Istio: `hack/istio/install-istio-via-istioctl.sh`
3. Install Kiali operator and server: `make build build-ui cluster-push operator-create kiali-create`

At this point, I thought I needed to build OSSMC (from its repo, do "make cluster-push") which pushes the image to the cluster after building it. But then it seems like that isn't useful because I have to run the 4.15 console locally?? What is the next steps?

I tried `yarn run start-console` from the OSSMC local repo, which starts the OS Console on port 9000 and 9001. But when I go to the console at 9000, I do not see "Service Mesh" menu items in the console.

**Comment by ferhoyos** [comment]
Hi @jmazzitelli, you have two options:

- Install Openshift 4.15 with latest CRC version.
- Install Openshift 4.14 with current crc-openshift.sh script. Then you have to execute `yarn start` in one terminal and `yarn start-console` in another terminal. Before executing the script you have to modify the console script to use versión 4.15

OPENSHIFT_VERSION=4.15

I think that by default it assumes you have Kiali running locally in `http://localhost:3001`
For other cases maybe you have to modify API_PROXY env variable in `.env.development` file.

**Review by jshaughn — COMMENTED** [review]
It took me a while to get a test setup working.  Outside of this PR we need to clarify the steps needed to get the console set up for development.  I would suggest removing the `make-prepare-dev-env` script, which had a few problems, and just list the manual steps required.  It is especially important to make sure devs know how to configure their kiali backend.  The default in `env.development` is assuming the `run-kiali.sh` default of `localhost:3001`, which is not what I had running.

As for the PR:
- non-blocking: the namespace dropdown did not update on close/open, with a new namespace I deployed.  It did update after I navigated from graph to overview.
- The Istio Config list page crashed for me.  I was using bookinfo and have master kiali deployed.
OSSMC:
image
Kiali:
image

Actually, everything else looked good to me.  Just need to understand the config list problem.

**Review by jshaughn — APPROVED** [review]
ON a second round of testing I could not recreate my issue with the Istio Config page crash.  I'm willing to believe it was an issue with my test environment as @josunect did multiple rounds of review without encountering a similar issue.  Even if it is a real issue there is not a way to debug it at the moment, so better to get this into the main branch for wider use.

Great job @ferhoyos!

**Pull request merged**
