### PR TITLE
[1.73] Include MessageCenter in OSSMC to show AlertUtils messages

### PR DESCRIPTION
**Pull request by ferhoyos**
Backport of #267 to v1.73 branch.

Issue: #264

### CODE REVIEW

**Comment by ferhoyos** [comment]
Do not merge until OSSM 2.5.0 is released.

**Comment by ferhoyos** [comment]
OSSM 2.5 is released, so we can merge backports to v1.73 branch

**Review by jshaughn — COMMENTED** [review]
Looks OK but Conflicts...

**Comment by ferhoyos** [comment]
It's true, let me rebase the PR

**Review by jshaughn — COMMENTED** [review]
This looks ok to me, although is it expected to have yarn.lock changes without package.json changes?

**Comment by ferhoyos** [comment]
Probably the `yarn.lock` changes are because of some previous backport PR created with cherry-pick that did not contain the correct `yarn.lock`.

**Comment by ferhoyos** [comment]
This `yarn.lock` update happens on multiple existing PRs for v1.73 branch, so they will probably get in conflict each other. If you agree @jshaughn, approve one of them and I will solve the conflicts for the rest of the PRs when it is merged.

**Pull request merged**
